export const directory = [
    {
        "PCID": 4,
        "PCName": "學生生涯輔導網",
        "CID": 3007,
        "Type": 17,
        "CName": "認識我自己",
        "AID": 0,
        "WebRoute": "Career/1",
        "IDPath": "4/3007",
        "cRank": 6,
        "nLevel": 2,
        "CategoryType": 1
    },
    {
        "PCID": 4,
        "PCName": "學生生涯輔導網",
        "CID": 3128,
        "Type": 17,
        "CName": "資源下載",
        "AID": 0,
        "WebRoute": "Career/122",
        "IDPath": "4/3128",
        "cRank": 208,
        "nLevel": 2,
        "CategoryType": 1
    },
    {
        "PCID": 4,
        "PCName": "學生生涯輔導網",
        "CID": 3151,
        "Type": 17,
        "CName": "相關連結",
        "AID": 0,
        "WebRoute": "Career/145",
        "IDPath": "4/3151",
        "cRank": 238,
        "nLevel": 2,
        "CategoryType": 1
    },
    {
        "PCID": 4,
        "PCName": "學生生涯輔導網",
        "CID": 3158,
        "Type": 7,
        "CName": "聯絡我們",
        "AID": 0,
        "WebRoute": "Career/152",
        "IDPath": "4/3158",
        "cRank": 245,
        "nLevel": 2,
        "CategoryType": 1
    },
    {
        "PCID": 843,
        "PCName": "財團法人技專院校入學測驗中心",
        "CID": 218,
        "Type": 5,
        "CName": "國教院影片",
        "AID": 0,
        "WebRoute": "https://stv.naer.edu.tw/redirect.html?ourl=/co_stv.php",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 847,
        "PCName": "國軍人才招募中心",
        "CID": 219,
        "Type": 5,
        "CName": "CIRN-性別平等教育議題教學示例",
        "AID": 0,
        "WebRoute": "https://cirn.moe.edu.tw/Issue/FilePage.aspx?sid=25&id=5&mid=849",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 853,
        "PCName": "勞動力發展署",
        "CID": 220,
        "Type": 5,
        "CName": "素養導向的教與學--給孩子面對未來的能力",
        "AID": 0,
        "WebRoute": "https://www.youtube.com/watch?v=Iw4-9J4zcSU",
        "IDPath": "",
        "cRank": 242,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 853,
        "PCName": "勞動力發展署",
        "CID": 221,
        "Type": 5,
        "CName": "國教院針對素養導向說明",
        "AID": 0,
        "WebRoute": "https://www.youtube.com/watch?v=kOIennbNtzs",
        "IDPath": "",
        "cRank": 242,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 853,
        "PCName": "勞動力發展署",
        "CID": 222,
        "Type": 5,
        "CName": "大考中心主任劉孟奇新課綱命題演講",
        "AID": 0,
        "WebRoute": "https://www.youtube.com/watch?v=oCM9T_v5pJ4",
        "IDPath": "",
        "cRank": 242,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 1188,
        "PCName": "按鈕 (Buttons)",
        "CID": 417,
        "Type": 5,
        "CName": "1.學生懷孕受教權維護及輔導協助要點",
        "AID": 0,
        "WebRoute": "https://edu.law.moe.gov.tw/",
        "IDPath": "",
        "cRank": 30,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 1188,
        "PCName": "按鈕 (Buttons)",
        "CID": 418,
        "Type": 5,
        "CName": "2.教育部性別平等教育委員會設置要點",
        "AID": 0,
        "WebRoute": "https://edu.law.moe.gov.tw/",
        "IDPath": "",
        "cRank": 30,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 1188,
        "PCName": "按鈕 (Buttons)",
        "CID": 419,
        "Type": 5,
        "CName": "3.教育部性別平等教育委員會運作參考模式及流程",
        "AID": 0,
        "WebRoute": "https://www.gender.edu.tw/web/index.php/m2/m2_02_03_01?sid=24",
        "IDPath": "",
        "cRank": 30,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 1188,
        "PCName": "按鈕 (Buttons)",
        "CID": 420,
        "Type": 5,
        "CName": "4.學校校園性侵害或性騷擾事件通報處理程序參考流程圖",
        "AID": 0,
        "WebRoute": "https://www.gender.edu.tw/web/index.php/m2/m2_05_03_01?sid=67",
        "IDPath": "",
        "cRank": 30,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 1188,
        "PCName": "按鈕 (Buttons)",
        "CID": 421,
        "Type": 5,
        "CName": "5.各級學校校園性侵害性騷擾暨性別事件處理程序檢核表",
        "AID": 0,
        "WebRoute": "https://www.gender.edu.tw/web/index.php/m2/m2_05_03_01?sid=67",
        "IDPath": "",
        "cRank": 30,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 1188,
        "PCName": "按鈕 (Buttons)",
        "CID": 422,
        "Type": 5,
        "CName": "6.校園性侵害性騷擾或性霸凌調查及處理參考流程Q＆A",
        "AID": 0,
        "WebRoute": "http://gender.nhes.edu.tw/images/rule/1/1-9.pdf",
        "IDPath": "",
        "cRank": 30,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 1188,
        "PCName": "按鈕 (Buttons)",
        "CID": 423,
        "Type": 5,
        "CName": "7.各級學校及幼兒園處理性侵害或性騷擾事件之通報及輔導處理流程",
        "AID": 0,
        "WebRoute": "https://www.gender.edu.tw/web/index.php/m2/m2_05_03_01?sid=67",
        "IDPath": "",
        "cRank": 30,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 1188,
        "PCName": "按鈕 (Buttons)",
        "CID": 424,
        "Type": 5,
        "CName": "8.教育部處理違反性別平等教育法事件處理程序及裁罰基準",
        "AID": 0,
        "WebRoute": "http://edu.law.moe.gov.tw/LawContent.aspx?id=GL001114",
        "IDPath": "",
        "cRank": 30,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 1188,
        "PCName": "按鈕 (Buttons)",
        "CID": 425,
        "Type": 5,
        "CName": "9.教育部國民及學前教育署推動高級中等以下學校性別平等教育工作小組設置要點",
        "AID": 0,
        "WebRoute": "https://www.k12ea.gov.tw/err.html?aspxerrorpath=/ap/affair_view.aspx",
        "IDPath": "",
        "cRank": 30,
        "nLevel": 5,
        "CategoryType": 0
    },
    {
        "PCID": 3007,
        "PCName": "認識我自己",
        "CID": 3649,
        "Type": 5,
        "CName": "測驗評量",
        "AID": 0,
        "WebRoute": "Career/1/2",
        "IDPath": "4/3007/3649",
        "cRank": 7,
        "nLevel": 3,
        "CategoryType": 4
    },
    {
        "PCID": 3007,
        "PCName": "認識我自己",
        "CID": 3650,
        "Type": 5,
        "CName": "探索活動",
        "AID": 0,
        "WebRoute": "Career/1/10",
        "IDPath": "4/3007/3650",
        "cRank": 16,
        "nLevel": 3,
        "CategoryType": 4
    },
    {
        "PCID": 3007,
        "PCName": "認識我自己",
        "CID": 3919,
        "Type": 19,
        "CName": "大學營隊",
        "AID": 0,
        "WebRoute": "Career/1/co",
        "IDPath": "4/3007/3919",
        "cRank": 23,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3007,
        "PCName": "認識我自己",
        "CID": 3924,
        "Type": 6,
        "CName": "表單",
        "AID": 0,
        "WebRoute": "Career/1/form",
        "IDPath": "4/3007/3924",
        "cRank": 25,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3007,
        "PCName": "認識我自己",
        "CID": 3925,
        "Type": 11,
        "CName": "PDF",
        "AID": 0,
        "WebRoute": "Career/1/PDF",
        "IDPath": "4/3007/3925",
        "cRank": 26,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3007,
        "PCName": "認識我自己",
        "CID": 3926,
        "Type": 16,
        "CName": "標籤",
        "AID": 0,
        "WebRoute": "Career/1/標籤",
        "IDPath": "4/3007/3926",
        "cRank": 27,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3007,
        "PCName": "認識我自己",
        "CID": 3927,
        "Type": 18,
        "CName": "相簿",
        "AID": 0,
        "WebRoute": "Career/1/album",
        "IDPath": "4/3007/3927",
        "cRank": 28,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3007,
        "PCName": "認識我自己",
        "CID": 3928,
        "Type": 4,
        "CName": "公告",
        "AID": 0,
        "WebRoute": "Career/1/post",
        "IDPath": "4/3007/3928",
        "cRank": 29,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3007,
        "PCName": "認識我自己",
        "CID": 3932,
        "Type": 5,
        "CName": "資源連結",
        "AID": 0,
        "WebRoute": "Career/1/resssq",
        "IDPath": "4/3007/3932",
        "cRank": 30,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3007,
        "PCName": "認識我自己",
        "CID": 3933,
        "Type": 14,
        "CName": "FAQ",
        "AID": 0,
        "WebRoute": "Career/1/Faqq",
        "IDPath": "4/3007/3933",
        "cRank": 31,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3128,
        "PCName": "資源下載",
        "CID": 3675,
        "Type": 10,
        "CName": "計畫與成果",
        "AID": 0,
        "WebRoute": "Career/122/123",
        "IDPath": "4/3128/3675",
        "cRank": 209,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3128,
        "PCName": "資源下載",
        "CID": 3676,
        "Type": 10,
        "CName": "國中專區",
        "AID": 0,
        "WebRoute": "Career/122/128",
        "IDPath": "4/3128/3676",
        "cRank": 216,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3128,
        "PCName": "資源下載",
        "CID": 3677,
        "Type": 10,
        "CName": "高中專區",
        "AID": 0,
        "WebRoute": "Career/122/136",
        "IDPath": "4/3128/3677",
        "cRank": 225,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3128,
        "PCName": "資源下載",
        "CID": 3678,
        "Type": 10,
        "CName": "其他",
        "AID": 0,
        "WebRoute": "Career/122/143",
        "IDPath": "4/3128/3678",
        "cRank": 233,
        "nLevel": 3,
        "CategoryType": 0
    },
    {
        "PCID": 3151,
        "PCName": "相關連結",
        "CID": 3152,
        "Type": 5,
        "CName": "政府單位",
        "AID": 0,
        "WebRoute": "Career/145/146",
        "IDPath": "4/3151/3152",
        "cRank": 239,
        "nLevel": 3,
        "CategoryType": 4
    },
    {
        "PCID": 3151,
        "PCName": "相關連結",
        "CID": 3153,
        "Type": 5,
        "CName": "生涯網站",
        "AID": 0,
        "WebRoute": "Career/145/147",
        "IDPath": "4/3151/3153",
        "cRank": 240,
        "nLevel": 3,
        "CategoryType": 4
    },
    {
        "PCID": 3151,
        "PCName": "相關連結",
        "CID": 3154,
        "Type": 5,
        "CName": "升學網站",
        "AID": 0,
        "WebRoute": "Career/145/148",
        "IDPath": "4/3151/3154",
        "cRank": 241,
        "nLevel": 3,
        "CategoryType": 4
    },
    {
        "PCID": 3151,
        "PCName": "相關連結",
        "CID": 3155,
        "Type": 5,
        "CName": "就業網站",
        "AID": 0,
        "WebRoute": "Career/145/149",
        "IDPath": "4/3151/3155",
        "cRank": 242,
        "nLevel": 3,
        "CategoryType": 4
    },
    {
        "PCID": 3151,
        "PCName": "相關連結",
        "CID": 3156,
        "Type": 5,
        "CName": "其他連結",
        "AID": 0,
        "WebRoute": "Career/145/150",
        "IDPath": "4/3151/3156",
        "cRank": 243,
        "nLevel": 3,
        "CategoryType": 4
    },
    {
        "PCID": 3152,
        "PCName": "政府單位",
        "CID": 833,
        "Type": 5,
        "CName": "教育部國民及學前教育署",
        "AID": 0,
        "WebRoute": "https://www.k12ea.gov.tw/",
        "IDPath": "",
        "cRank": 239,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3152,
        "PCName": "政府單位",
        "CID": 834,
        "Type": 5,
        "CName": "青年教育與就業儲蓄帳戶",
        "AID": 0,
        "WebRoute": "https://young.cloud.ncnu.edu.tw/SignUp",
        "IDPath": "",
        "cRank": 239,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3152,
        "PCName": "政府單位",
        "CID": 835,
        "Type": 5,
        "CName": "壯遊體驗學習網",
        "AID": 0,
        "WebRoute": "https://youthtravel.tw/",
        "IDPath": "",
        "cRank": 239,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3153,
        "PCName": "生涯網站",
        "CID": 836,
        "Type": 5,
        "CName": "普通高級中學課程生涯規劃學科中心",
        "AID": 0,
        "WebRoute": "https://ghresource.mt.ntnu.edu.tw/nss/p/CareerPlanning",
        "IDPath": "",
        "cRank": 240,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3153,
        "PCName": "生涯網站",
        "CID": 837,
        "Type": 5,
        "CName": "華人生涯網",
        "AID": 0,
        "WebRoute": "http://careering.heart.net.tw/style/",
        "IDPath": "",
        "cRank": 240,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 838,
        "Type": 5,
        "CName": "大學入學考試中心",
        "AID": 0,
        "WebRoute": "https://www.ceec.edu.tw/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 839,
        "Type": 5,
        "CName": "ColleGo!大學選才與高中育才輔助系統",
        "AID": 0,
        "WebRoute": "https://collego.edu.tw/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 840,
        "Type": 5,
        "CName": "大學考試入學分發委員會",
        "AID": 0,
        "WebRoute": "https://www.uac.edu.tw/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 841,
        "Type": 5,
        "CName": "大學甄選入學委員會",
        "AID": 0,
        "WebRoute": "https://www.cac.edu.tw/cacportal/index.php",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 842,
        "Type": 5,
        "CName": "技專校院招生策進總會",
        "AID": 0,
        "WebRoute": "https://www.techadmi.edu.tw/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 843,
        "Type": 5,
        "CName": "財團法人技專院校入學測驗中心",
        "AID": 0,
        "WebRoute": "https://www.tcte.edu.tw/page_new.php",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 844,
        "Type": 5,
        "CName": "技訊網",
        "AID": 0,
        "WebRoute": "https://techexpo.moe.edu.tw/search/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 845,
        "Type": 5,
        "CName": "運動成績優良學生升學輔導網站",
        "AID": 0,
        "WebRoute": "https://lulu.ntus.edu.tw/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 846,
        "Type": 5,
        "CName": "警察專科學校招生",
        "AID": 0,
        "WebRoute": "https://exam.tpa.edu.tw/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 847,
        "Type": 5,
        "CName": "國軍人才招募中心",
        "AID": 0,
        "WebRoute": "https://rdrc.mnd.gov.tw/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 848,
        "Type": 5,
        "CName": "中央警察大學招生",
        "AID": 0,
        "WebRoute": "https://www.cpu.edu.tw/p/412-1000-137.php?Lang=zh-tw",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 849,
        "Type": 5,
        "CName": "臺北藝術大學",
        "AID": 0,
        "WebRoute": "https://w3.tnua.edu.tw/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 850,
        "Type": 5,
        "CName": "臺灣藝術大學",
        "AID": 0,
        "WebRoute": "https://www.ntua.edu.tw/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 851,
        "Type": 5,
        "CName": "教育部國教署特教網路中心",
        "AID": 0,
        "WebRoute": "https://www.aide.edu.tw/ischool/publish_page/0/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3154,
        "PCName": "升學網站",
        "CID": 852,
        "Type": 5,
        "CName": "大學多元入學升學網",
        "AID": 0,
        "WebRoute": "http://nsdua.moe.edu.tw/#/",
        "IDPath": "",
        "cRank": 241,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3155,
        "PCName": "就業網站",
        "CID": 853,
        "Type": 5,
        "CName": "勞動力發展署",
        "AID": 0,
        "WebRoute": "https://www.wda.gov.tw/",
        "IDPath": "",
        "cRank": 242,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3155,
        "PCName": "就業網站",
        "CID": 854,
        "Type": 5,
        "CName": "台灣就業通",
        "AID": 0,
        "WebRoute": "https://www.taiwanjobs.gov.tw/home109/index.aspx",
        "IDPath": "",
        "cRank": 242,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3155,
        "PCName": "就業網站",
        "CID": 855,
        "Type": 5,
        "CName": "104人力銀行",
        "AID": 0,
        "WebRoute": "https://www.104.com.tw/jobs/main/",
        "IDPath": "",
        "cRank": 242,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3155,
        "PCName": "就業網站",
        "CID": 856,
        "Type": 5,
        "CName": "1111 人力銀行",
        "AID": 0,
        "WebRoute": "https://www.1111.com.tw/",
        "IDPath": "",
        "cRank": 242,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3155,
        "PCName": "就業網站",
        "CID": 857,
        "Type": 5,
        "CName": "O*Net Online",
        "AID": 0,
        "WebRoute": "https://www.onetonline.org/",
        "IDPath": "",
        "cRank": 242,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3155,
        "PCName": "就業網站",
        "CID": 858,
        "Type": 5,
        "CName": "Career 就業情報網",
        "AID": 0,
        "WebRoute": "http://career.jtg.com.tw/",
        "IDPath": "",
        "cRank": 242,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3649,
        "PCName": "測驗評量",
        "CID": 1046,
        "Type": 5,
        "CName": "大學入學考試中心興趣量表",
        "AID": 0,
        "WebRoute": "https://career.ceec.edu.tw/StudentSection/Introduce",
        "IDPath": "",
        "cRank": 7,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3649,
        "PCName": "測驗評量",
        "CID": 1047,
        "Type": 5,
        "CName": "大學入學考試中心大學學系探索量表",
        "AID": 0,
        "WebRoute": "https://career.ceec.edu.tw/StudentSection/Introduce",
        "IDPath": "",
        "cRank": 7,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3649,
        "PCName": "測驗評量",
        "CID": 1048,
        "Type": 5,
        "CName": "華人生涯網職業興趣量表",
        "AID": 0,
        "WebRoute": "http://careering.ncue.edu.tw/style/?13",
        "IDPath": "",
        "cRank": 7,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3649,
        "PCName": "測驗評量",
        "CID": 1049,
        "Type": 5,
        "CName": "「我喜歡做的事」興趣測驗",
        "AID": 0,
        "WebRoute": "https://exam.taiwanjobs.gov.tw/jobexam/L03/L0301",
        "IDPath": "",
        "cRank": 7,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3649,
        "PCName": "測驗評量",
        "CID": 1050,
        "Type": 5,
        "CName": "華人生涯網職業組合卡",
        "AID": 0,
        "WebRoute": "http://careering.ncue.edu.tw/ge/b001-1_1.aspx",
        "IDPath": "",
        "cRank": 7,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3649,
        "PCName": "測驗評量",
        "CID": 1051,
        "Type": 5,
        "CName": "\t華人生涯網生涯開展力量表",
        "AID": 0,
        "WebRoute": "http://careering.ncue.edu.tw/style/?22",
        "IDPath": "",
        "cRank": 7,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3650,
        "PCName": "探索活動",
        "CID": 1052,
        "Type": 5,
        "CName": "1111九大職能星",
        "AID": 0,
        "WebRoute": "https://assessment.1111.com.tw/cstar/index.aspx",
        "IDPath": "",
        "cRank": 16,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3650,
        "PCName": "探索活動",
        "CID": 1053,
        "Type": 5,
        "CName": "1111Holland學涯暨職涯興趣測驗",
        "AID": 0,
        "WebRoute": "https://www.hollandexam.com/",
        "IDPath": "",
        "cRank": 16,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3650,
        "PCName": "探索活動",
        "CID": 1054,
        "Type": 5,
        "CName": "104職業適性測驗",
        "AID": 0,
        "WebRoute": "https://guide.104.com.tw/personality",
        "IDPath": "",
        "cRank": 16,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3650,
        "PCName": "探索活動",
        "CID": 1055,
        "Type": 5,
        "CName": "104生涯興趣測驗",
        "AID": 0,
        "WebRoute": "https://guide.104.com.tw/",
        "IDPath": "",
        "cRank": 16,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3650,
        "PCName": "探索活動",
        "CID": 1056,
        "Type": 5,
        "CName": "104職涯興趣量表",
        "AID": 0,
        "WebRoute": "https://pda.104.com.tw/my104/exam/index?u=o01t1x",
        "IDPath": "",
        "cRank": 16,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3650,
        "PCName": "探索活動",
        "CID": 1057,
        "Type": 5,
        "CName": "104工作價值觀量表",
        "AID": 0,
        "WebRoute": "https://pda.104.com.tw/my104/exam/index?u=o01t1x",
        "IDPath": "",
        "cRank": 16,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3919,
        "PCName": "大學營隊",
        "CID": 3922,
        "Type": 21,
        "CName": "大學營隊",
        "AID": 0,
        "WebRoute": "Career/1/co/CollegeCampDetail",
        "IDPath": "4/3007/3919/3922",
        "cRank": 24,
        "nLevel": 4,
        "CategoryType": 0
    },
    {
        "PCID": 3932,
        "PCName": "資源連結",
        "CID": 1188,
        "Type": 5,
        "CName": "按鈕 (Buttons)",
        "AID": 0,
        "WebRoute": "https://bootstrap5.hexschool.com/docs/5.1/components/buttons/",
        "IDPath": "",
        "cRank": 30,
        "nLevel": 4,
        "CategoryType": 0
    }
]